/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactMessage {
    messageId: string;
    agentId: string;
    sender: Principal;
    message: string;
    timestamp: Time;
}
export type Time = bigint;
export interface InsuranceInquiry {
    status: InquiryStatus;
    insuranceType: InsuranceType;
    user: Principal;
    timestamp: Time;
    details: string;
    inquiryId: string;
}
export interface Agent {
    name: string;
    agentId: string;
    email: string;
    specialization: Array<InsuranceType>;
    phone: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface InsurancePlan {
    insuranceType: InsuranceType;
    features: Array<string>;
    premium: bigint;
    planId: string;
    name: string;
    coverageAmount: bigint;
}
export enum InquiryStatus {
    resolved = "resolved",
    pending = "pending",
    inReview = "inReview"
}
export enum InsuranceType {
    auto = "auto",
    home = "home",
    life = "life",
    health = "health"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAgent(agent: Agent): Promise<void>;
    addInsurancePlan(plan: InsurancePlan): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllAgents(): Promise<Array<Agent>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllInsuranceInquiries(): Promise<Array<InsuranceInquiry>>;
    getAllInsurancePlans(): Promise<Array<InsurancePlan>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactMessagesForAgent(agentId: string): Promise<Array<ContactMessage>>;
    getInsuranceInquiriesByType(insuranceType: InsuranceType): Promise<Array<InsuranceInquiry>>;
    getInsurancePlansByType(insuranceType: InsuranceType): Promise<Array<InsurancePlan>>;
    getMyInsuranceInquiries(): Promise<Array<InsuranceInquiry>>;
    getPendingInsuranceInquiries(): Promise<Array<InsuranceInquiry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessageToAgent(agentId: string, message: string): Promise<string>;
    submitInsuranceInquiry(insuranceType: InsuranceType, details: string): Promise<string>;
    updateInquiryStatus(inquiryId: string, status: InquiryStatus): Promise<void>;
}
import type { Agent as _Agent, InquiryStatus as _InquiryStatus, InsuranceInquiry as _InsuranceInquiry, InsurancePlan as _InsurancePlan, InsuranceType as _InsuranceType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAgent(arg0: Agent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgent(to_candid_Agent_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgent(to_candid_Agent_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInsurancePlan(arg0: InsurancePlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInsurancePlan(to_candid_InsurancePlan_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInsurancePlan(to_candid_InsurancePlan_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllInsuranceInquiries(): Promise<Array<InsuranceInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInsuranceInquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInsuranceInquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInsurancePlans(): Promise<Array<InsurancePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInsurancePlans();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInsurancePlans();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactMessagesForAgent(arg0: string): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessagesForAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessagesForAgent(arg0);
            return result;
        }
    }
    async getInsuranceInquiriesByType(arg0: InsuranceType): Promise<Array<InsuranceInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsuranceInquiriesByType(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsuranceInquiriesByType(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsurancePlansByType(arg0: InsuranceType): Promise<Array<InsurancePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsurancePlansByType(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsurancePlansByType(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInsuranceInquiries(): Promise<Array<InsuranceInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInsuranceInquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInsuranceInquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingInsuranceInquiries(): Promise<Array<InsuranceInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingInsuranceInquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingInsuranceInquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessageToAgent(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToAgent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToAgent(arg0, arg1);
            return result;
        }
    }
    async submitInsuranceInquiry(arg0: InsuranceType, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInsuranceInquiry(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInsuranceInquiry(to_candid_InsuranceType_n4(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateInquiryStatus(arg0: string, arg1: InquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Agent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceInquiry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceInquiry): InsuranceInquiry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InsurancePlan_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsurancePlan): InsurancePlan {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceType): InsuranceType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    agentId: string;
    email: string;
    specialization: Array<_InsuranceType>;
    phone: string;
}): {
    name: string;
    agentId: string;
    email: string;
    specialization: Array<InsuranceType>;
    phone: string;
} {
    return {
        name: value.name,
        agentId: value.agentId,
        email: value.email,
        specialization: from_candid_vec_n13(_uploadFile, _downloadFile, value.specialization),
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InquiryStatus;
    insuranceType: _InsuranceType;
    user: Principal;
    timestamp: _Time;
    details: string;
    inquiryId: string;
}): {
    status: InquiryStatus;
    insuranceType: InsuranceType;
    user: Principal;
    timestamp: Time;
    details: string;
    inquiryId: string;
} {
    return {
        status: from_candid_InquiryStatus_n19(_uploadFile, _downloadFile, value.status),
        insuranceType: from_candid_InsuranceType_n14(_uploadFile, _downloadFile, value.insuranceType),
        user: value.user,
        timestamp: value.timestamp,
        details: value.details,
        inquiryId: value.inquiryId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insuranceType: _InsuranceType;
    features: Array<string>;
    premium: bigint;
    planId: string;
    name: string;
    coverageAmount: bigint;
}): {
    insuranceType: InsuranceType;
    features: Array<string>;
    premium: bigint;
    planId: string;
    name: string;
    coverageAmount: bigint;
} {
    return {
        insuranceType: from_candid_InsuranceType_n14(_uploadFile, _downloadFile, value.insuranceType),
        features: value.features,
        premium: value.premium,
        planId: value.planId,
        name: value.name,
        coverageAmount: value.coverageAmount
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    auto: null;
} | {
    home: null;
} | {
    life: null;
} | {
    health: null;
}): InsuranceType {
    return "auto" in value ? InsuranceType.auto : "home" in value ? InsuranceType.home : "life" in value ? InsuranceType.life : "health" in value ? InsuranceType.health : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    inReview: null;
}): InquiryStatus {
    return "resolved" in value ? InquiryStatus.resolved : "pending" in value ? InquiryStatus.pending : "inReview" in value ? InquiryStatus.inReview : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceType>): Array<InsuranceType> {
    return value.map((x)=>from_candid_InsuranceType_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceInquiry>): Array<InsuranceInquiry> {
    return value.map((x)=>from_candid_InsuranceInquiry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsurancePlan>): Array<InsurancePlan> {
    return value.map((x)=>from_candid_InsurancePlan_n22(_uploadFile, _downloadFile, x));
}
function to_candid_Agent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Agent): _Agent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_InsurancePlan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsurancePlan): _InsurancePlan {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_InsuranceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceType): _InsuranceType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    agentId: string;
    email: string;
    specialization: Array<InsuranceType>;
    phone: string;
}): {
    name: string;
    agentId: string;
    email: string;
    specialization: Array<_InsuranceType>;
    phone: string;
} {
    return {
        name: value.name,
        agentId: value.agentId,
        email: value.email,
        specialization: to_candid_vec_n3(_uploadFile, _downloadFile, value.specialization),
        phone: value.phone
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insuranceType: InsuranceType;
    features: Array<string>;
    premium: bigint;
    planId: string;
    name: string;
    coverageAmount: bigint;
}): {
    insuranceType: _InsuranceType;
    features: Array<string>;
    premium: bigint;
    planId: string;
    name: string;
    coverageAmount: bigint;
} {
    return {
        insuranceType: to_candid_InsuranceType_n4(_uploadFile, _downloadFile, value.insuranceType),
        features: value.features,
        premium: value.premium,
        planId: value.planId,
        name: value.name,
        coverageAmount: value.coverageAmount
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    resolved: null;
} | {
    pending: null;
} | {
    inReview: null;
} {
    return value == InquiryStatus.resolved ? {
        resolved: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.inReview ? {
        inReview: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceType): {
    auto: null;
} | {
    home: null;
} | {
    life: null;
} | {
    health: null;
} {
    return value == InsuranceType.auto ? {
        auto: null
    } : value == InsuranceType.home ? {
        home: null
    } : value == InsuranceType.life ? {
        life: null
    } : value == InsuranceType.health ? {
        health: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InsuranceType>): Array<_InsuranceType> {
    return value.map((x)=>to_candid_InsuranceType_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
