/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InsuranceType = IDL.Variant({
  'auto' : IDL.Null,
  'home' : IDL.Null,
  'life' : IDL.Null,
  'health' : IDL.Null,
});
export const Agent = IDL.Record({
  'name' : IDL.Text,
  'agentId' : IDL.Text,
  'email' : IDL.Text,
  'specialization' : IDL.Vec(InsuranceType),
  'phone' : IDL.Text,
});
export const InsurancePlan = IDL.Record({
  'insuranceType' : InsuranceType,
  'features' : IDL.Vec(IDL.Text),
  'premium' : IDL.Nat,
  'planId' : IDL.Text,
  'name' : IDL.Text,
  'coverageAmount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'messageId' : IDL.Text,
  'agentId' : IDL.Text,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const InquiryStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'inReview' : IDL.Null,
});
export const InsuranceInquiry = IDL.Record({
  'status' : InquiryStatus,
  'insuranceType' : InsuranceType,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
  'inquiryId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAgent' : IDL.Func([Agent], [], []),
  'addInsurancePlan' : IDL.Func([InsurancePlan], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllInsuranceInquiries' : IDL.Func(
      [],
      [IDL.Vec(InsuranceInquiry)],
      ['query'],
    ),
  'getAllInsurancePlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessagesForAgent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'getInsuranceInquiriesByType' : IDL.Func(
      [InsuranceType],
      [IDL.Vec(InsuranceInquiry)],
      ['query'],
    ),
  'getInsurancePlansByType' : IDL.Func(
      [InsuranceType],
      [IDL.Vec(InsurancePlan)],
      ['query'],
    ),
  'getMyInsuranceInquiries' : IDL.Func(
      [],
      [IDL.Vec(InsuranceInquiry)],
      ['query'],
    ),
  'getPendingInsuranceInquiries' : IDL.Func(
      [],
      [IDL.Vec(InsuranceInquiry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessageToAgent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'submitInsuranceInquiry' : IDL.Func(
      [InsuranceType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InsuranceType = IDL.Variant({
    'auto' : IDL.Null,
    'home' : IDL.Null,
    'life' : IDL.Null,
    'health' : IDL.Null,
  });
  const Agent = IDL.Record({
    'name' : IDL.Text,
    'agentId' : IDL.Text,
    'email' : IDL.Text,
    'specialization' : IDL.Vec(InsuranceType),
    'phone' : IDL.Text,
  });
  const InsurancePlan = IDL.Record({
    'insuranceType' : InsuranceType,
    'features' : IDL.Vec(IDL.Text),
    'premium' : IDL.Nat,
    'planId' : IDL.Text,
    'name' : IDL.Text,
    'coverageAmount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'messageId' : IDL.Text,
    'agentId' : IDL.Text,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const InquiryStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'inReview' : IDL.Null,
  });
  const InsuranceInquiry = IDL.Record({
    'status' : InquiryStatus,
    'insuranceType' : InsuranceType,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
    'inquiryId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAgent' : IDL.Func([Agent], [], []),
    'addInsurancePlan' : IDL.Func([InsurancePlan], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllInsuranceInquiries' : IDL.Func(
        [],
        [IDL.Vec(InsuranceInquiry)],
        ['query'],
      ),
    'getAllInsurancePlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessagesForAgent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getInsuranceInquiriesByType' : IDL.Func(
        [InsuranceType],
        [IDL.Vec(InsuranceInquiry)],
        ['query'],
      ),
    'getInsurancePlansByType' : IDL.Func(
        [InsuranceType],
        [IDL.Vec(InsurancePlan)],
        ['query'],
      ),
    'getMyInsuranceInquiries' : IDL.Func(
        [],
        [IDL.Vec(InsuranceInquiry)],
        ['query'],
      ),
    'getPendingInsuranceInquiries' : IDL.Func(
        [],
        [IDL.Vec(InsuranceInquiry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessageToAgent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'submitInsuranceInquiry' : IDL.Func(
        [InsuranceType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };