/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'name' : string,
  'agentId' : string,
  'email' : string,
  'specialization' : Array<InsuranceType>,
  'phone' : string,
}
export interface ContactMessage {
  'messageId' : string,
  'agentId' : string,
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type InquiryStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'inReview' : null };
export interface InsuranceInquiry {
  'status' : InquiryStatus,
  'insuranceType' : InsuranceType,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
  'inquiryId' : string,
}
export interface InsurancePlan {
  'insuranceType' : InsuranceType,
  'features' : Array<string>,
  'premium' : bigint,
  'planId' : string,
  'name' : string,
  'coverageAmount' : bigint,
}
export type InsuranceType = { 'auto' : null } |
  { 'home' : null } |
  { 'life' : null } |
  { 'health' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAgent' : ActorMethod<[Agent], undefined>,
  'addInsurancePlan' : ActorMethod<[InsurancePlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllInsuranceInquiries' : ActorMethod<[], Array<InsuranceInquiry>>,
  'getAllInsurancePlans' : ActorMethod<[], Array<InsurancePlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessagesForAgent' : ActorMethod<[string], Array<ContactMessage>>,
  'getInsuranceInquiriesByType' : ActorMethod<
    [InsuranceType],
    Array<InsuranceInquiry>
  >,
  'getInsurancePlansByType' : ActorMethod<
    [InsuranceType],
    Array<InsurancePlan>
  >,
  'getMyInsuranceInquiries' : ActorMethod<[], Array<InsuranceInquiry>>,
  'getPendingInsuranceInquiries' : ActorMethod<[], Array<InsuranceInquiry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessageToAgent' : ActorMethod<[string, string], string>,
  'submitInsuranceInquiry' : ActorMethod<[InsuranceType, string], string>,
  'updateInquiryStatus' : ActorMethod<[string, InquiryStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];